name: CD_pipline
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: python
    steps:
      - uses: actions/checkout@v3
      - name: Connect via SSH
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa ubuntu@54.86.69.72 "cd fastapi-bbok-project && git pull"
