name: CD_pipline
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: python
    steps:
      - uses: actions/checkout@v3
      - name: Connect via SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./id_rsa
          chmod 400 ./id_rsa
          mkdir -p ~/.ssh/
          touch ~/.ssh/known_hosts
          ssh-keyscan 107.23.103.1 >> ~/.ssh/known_hosts
          ssh -i ./id_rsa ubuntu@107.23.103.1 "mkdir -p /tmp/book_project"
          scp -i ./id_rsa -r ./* ubuntu@107.23.103.1:/tmp/book_project/
          ssh -i ./id_rsa ubuntu@107.23.103.1 "pip3 install -r requirement.txt && sudo pkill fastapi && sudo pkill uvicorn && fastapi run"
