name: CD_pipline
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: python
    steps:
      - uses: actions/checkout@v3
      - name: Connect via SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > id_rsa
          chmod 400 id_rsa
          pip3 install --upgrade fabric
          fab --f fabfile.py deploy