name: CD_pipline
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: python
    steps:
      - uses: actions/checkout@v3
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 54.86.69.72
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/fastapi-book-project && git pull && sudo apt update && pip install --upgrade pip && pip install -r requirements.txt && sudo systemctl restart myapp            
